### ISSUE TITLE
为什么删除节点和链接节点没有用啊

### ISSUE THREAD

**Issue by chqyys** [chachaxw/react-neo4j#10]

**Comment by chachaxw** [comment]
@chqyys 添加编辑删除节点已经修复，添加节点连接未完成，原本是想做成可视化的那种，可惜没空。

**Comment by chqyys** [comment]
谢谢您的回复。就是删除节点和修改节点其实我看您的代码也看懂了，自己也进行了修改。感觉主要还是节点link那块不知道怎么修改。不过还是感谢您的代码，让我能学到更多。

**Comment by chqyys** [comment]
谢谢您的回复。就是删除节点和修改节点其实我看您的代码也看懂了，自己也进行了修改。感觉主要还是节点link那块不知道怎么修改。不过还是感谢您的代码，让我能学到更多。

**Comment by chachaxw** [comment]
@chqyys link那一块简单的交互就是，点击Link按钮，显示弹窗，选择目标节点就可以了。不过我其实想把这个操作可视化，不想用弹窗。
